default["shelter"]["base_path"] = "/usr/shelter"
default["shelter"]["log_filename"] = "var/log/shelter.log"
default["shelter"]["db_name"] = "shelter"
default["shelter"]["db_uri"] = "localhost:27017"
default["shelter"]["scan_resolver"] = "8.8.8.8"
default["shelter"]["scan_resolver_port"] = "53"
